add: section cards
scesi/3D_Printer_event_landing_page pull request #6
Opened 2024-10-20 02:11 UTC by NahuelTG

2024-10-20 19:11 UTC, MircoPilcoPeralta requested changes

2024-10-20 19:11 UTC, MircoPilcoPeralta commented on src/pages/index.astro
agrega los 3 guiones para que la página se mantenga funcionando

2024-10-20 19:11 UTC, MircoPilcoPeralta commented on src/pages/index.astro
> +         <Cards />
como recomendación, pienso que deberías colocar el componente Card dentro del vid con margen que se encuentra en la línea 16, para aprovechar el padding ya fijado

2024-10-20 19:11 UTC, MircoPilcoPeralta commented on src/components/Cards.astro
> +   @media (min-width: 768px) {
sería mejor utilizar los brekpoints que nos ofrece tailwind

2024-10-20 19:11 UTC, MircoPilcoPeralta commented on src/components/Cards.astro
> +      <header class="header-title">
Tengo mis dudas si se puede usar el tag header dentro de un componente y no solamente para contener la parte introductoria de la página

2024-10-20 19:11 UTC, MircoPilcoPeralta commented on src/components/Cards.astro
> +<section class="section-cards">
Me parece correcto que uses un section para encapsular la parte de la página que muestra las tarjetas

2024-10-20 19:11 UTC, MircoPilcoPeralta commented on src/components/Cards.astro
> +      <section class="section-content">
un section se utiliza para encerrar una sección, por ejemplo se puede utilizar para encerrar la sección de la localización, pero no debe usarse como un div(para todo), aquí te diría que no te compliques y uses divs

2024-10-20 19:11 UTC, MircoPilcoPeralta commented on src/components/Cards.astro
> +   <article class="article-card">
seria un articulo si el componente estuviera enfocado en representar publicaciones, entradas de blog o noticias y fuera independiente de la página, en este caso solo sería un div

2024-10-20 19:11 UTC, MircoPilcoPeralta commented on src/components/Cards.astro
> +   <article class="article-card">
cambia el tag a un div

2024-10-20 19:11 UTC, MircoPilcoPeralta commented on src/components/Cards.astro
> +      <section class="section-content">
cambialo a un div

2024-10-22 12:36 UTC, NahuelTG commented on src/pages/index.astro
Lo raro es que en mi codigo si esta dentro, y cuando lo subi en su momento tambien eso esta raro

2024-10-22 12:42 UTC, NahuelTG commented on src/components/Cards.astro
> +      <header class="header-title">
Segun mi investigacion y a lo que entendi, es posible https://miro.medium.com/v2/resize:fit:1400/1*Fmng2HslxCSvnHsTDEIr_g.png

2024-10-23 01:33 UTC, mar-vall approved these changes

2024-10-23 03:51 UTC, MircoPilcoPeralta approved these changes

2024-10-23 22:59 UTC, merged